/**
 * Author:  Jack R. Reames
 * Created: Apr 18, 2019
 */

DROP TABLE ORDERS;
DROP TABLE PRODUCTS;
DROP TABLE CUSTOMERS;

CREATE TABLE PRODUCTS (
    ID INT NOT NULL,
    PRODNAME VARCHAR(255),
    PRICE DOUBLE,
    INVENTORY INT,
    PRIMARY KEY(ID)
);

INSERT INTO PRODUCTS
VALUES (1, 'Standard 8.5" x 11"', 10.00, 200);
INSERT INTO PRODUCTS
VALUES (2, '8.5" x 11" Cardstock', 40.00, 75);

CREATE TABLE CUSTOMERS (
    ID INT NOT NULL,
    LNAME VARCHAR(255),
    FNAME VARCHAR(255),
    PHONE VARCHAR(255),
    EMAIL VARCHAR(255),
    PRIMARY KEY (ID)
);

INSERT INTO CUSTOMERS
VALUES (1, 'Fjorgerson', 'Thor', '(717)420-6969', 'thorfjorgerson@gmail.com');
INSERT INTO CUSTOMERS
VALUES (2, 'Public', 'John', '(555)555-5555', 'jqpublic@notarealwebsite.com');

CREATE TABLE ORDERS (
    ID INT NOT NULL,
    ORDERTIME BIGINT,
    AMOUNT INT,
    PRODID INT,
    CUSTID INT,
    PRIMARY KEY (ID),
    FOREIGN KEY (PRODID) REFERENCES PRODUCTS(ID),
    FOREIGN KEY (CUSTID) REFERENCES CUSTOMERS(ID)
);

INSERT INTO ORDERS
VALUES (1, 1, 1, 1, 1);
INSERT INTO ORDERS
VALUES (2, 2, 2, 2, 2);
